### PR TITLE
#157589765 Improved UI color

### PR DESCRIPTION
**Pull request by chukwuemekachm**
#### What does this PR do?
Improves UI color
#### Description of Task to be completed?
Change the UI colour combination to be uniform
#### What are the relevant pivotal tracker stories?
#157589765
#### Screenshots (if appropriate)
screenshot 109
screenshot 108

### CODE REVIEW

**Comment by paradisekelechi** [comment]
I cannot see background image locally here. Kindly fix that please @chukwuemekachm

**Comment by chukwuemekachm** [comment]
Sorry I forgot I was using VS code path intellisense

**Comment by paradisekelechi** [comment]
There isn't much contrast between the texts and background. Kindly implement that.

**Comment by chukwuemekachm** [comment]
I just resolved that

**Comment by paradisekelechi** [comment]
Looks good to me

**Pull request merged**
